### PR TITLE
Fix wrong itemtype

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Comment by richardlg62** [comment]
Hi @trasher , The fix don't work, the old itemtype from sub_type column generated by FusionInventory is "PluginFusioninventoryInventoryRuleEntity" and not "PluginFusinvinventoryRuleEntity"

**Comment by trasher** [comment]
@richardlg62 please try #104

**Comment by richardlg62** [comment]
Yes, it's worked ! the entity rules appear after the first installation of glpiinventory with this fix. (With Final release of GLPI 10.0.0)

image

Thanks you :)

**Comment by trasher** [comment]
Thank you for the feedback

**Pull request merged**
