### PR TITLE
fix(iprange): fix input size to prevent bad display

### PR DESCRIPTION
**Pull request by stonebuzz**
fix input size to prevent bad display

Before  : 
image

After  : 
image

Fix : #259

### CODE REVIEW

**Comment by orthagh** [comment]
maybe adding `.flex-nowrap` to the row should fix better

**Comment by stonebuzz** [comment]
> maybe adding `.flex-nowrap` to the row should fix better

add ```flex-nowrap``` class and re reduces the size a little bit (in order not to exceed the ```entity``` input) 

image

**Comment by g-bougard** [comment]
But something is still wrong: IP boxes overlaps when you stretch the window
image

**Comment by stonebuzz** [comment]
what is the size of your screen

**Comment by cedric-anne** [comment]
> what is the size of your screen

size does not matters

**Comment by stonebuzz** [comment]
> > what is the size of your screen
> 
> size does not matters

resolution ?

**Comment by stonebuzz** [comment]
it is because of the ```flex-nowrap``` on small resolution

**Comment by stonebuzz** [comment]
@g-bougard 

can you retry ?

**Comment by stonebuzz** [comment]
Can you retry ?

**Comment by g-bougard** [comment]
Seems good this way.

**Review by g-bougard — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
