### PR TITLE
fix(core): do not send XML to GLPI when contain <ERROR>

### PR DESCRIPTION
**Pull request by stonebuzz**
Try to prevent 
```shell
glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Key error is not handled in network devices conversion in /var/www/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php at line 1529
  Backtrace :
  ...ject/inventory_format/lib/php/Converter.php:380 Glpi\Inventory\Converter->convertNetworkInventory()
  ...ject/inventory_format/lib/php/Converter.php:323 Glpi\Inventory\Converter->convertTo01()
  src/Inventory/Inventory.php:141                    Glpi\Inventory\Converter->convert()
  src/Inventory/Request.php:265                      Glpi\Inventory\Inventory->setData()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:242                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  src/Inventory/Conf.php:287                         Glpi\Inventory\Conf->importFiles()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->displayImportFiles()
  public/index.php:82                                require()
```

when XML contain ```<ERROR>```

```XML
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <ERROR>
        <ID>210</ID>
        <MESSAGE>SNMP communication error: no response from host 13.22.7.57</MESSAGE>
        <TYPE>Printer</TYPE>
      </ERROR>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>5618276</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>hotline-xxxxx-2023-05-12-18-48-55</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

This type of XML is simply ignored on Fusion and has been for some time.

### CODE REVIEW

**Comment by g-bougard** [comment]
I'm against this PR as it involves normal netinventory XML submitted will be decoded 2 times: one time here to check if this is an error, and one more time into native inventory.

I'm agree we need to handle the error reporting in the plugin, but I would prefer the converter to be updated to accept the `ERROR` XML node so it can leave the plugin to decide what to do if it finds it.

**Comment by trasher** [comment]
Since proposed solution seems indeed a bit complex, I've tried to handle `error` key in inventory format converter. This ends with a refused equipment stored... That solves the initial issue; but this is still not correct. 
Note I've tested uploading a file to native inventory directly, not using the plusin (because I'm still not able to have something working -_-) - but as far as I've seen, plugin will never handle that correctly because it lacks information (and decoding XML would the only way to go).

I still not have any satisfying solution, maybe the refused equipment one would be the less crap one :/

**Comment by stonebuzz** [comment]
I will try to describe what I tried yesterday on GLPI
1 - Modification of ```inventory_format``` to allow the ```<ERROR>``` node 

```json
"error": {
    "properties": {
    "id": {
        "type": "integer"
    },
    "message": {
        "type": "string"
    },
    "type": {
        "type": "string"
    }
    }
},
```

2 - Injection of the XML file (via ```glpi-injector```) on ```GLPIInventory```.

3 - Subsequent error

```
glpi-injector -v -R -f error.xml -u http://127.0.0.1/GLPI/10.0-bugfixes/plugins/glpiinventory/
Loading error.xml...ERROR: Unhandled schema entry error
```

4 - Why

Because the XML contains ``<QUERY>SNMPQUERY</QUERY>```

So GLPI tries the action ```NETDISCOVERY_ACTION```

```php
    protected function handleAction($query, $content = null): bool
    {
        $this->query = $query;
        switch ($query) {
            case self::GET_PARAMS:
                $this->getParams($content);
                break;
            case self::CONTACT_ACTION:
                $this->contact($content);
                break;
            case self::PROLOG_QUERY:
                $this->prolog($content);
                break;
            case self::INVENT_QUERY:
            case self::INVENT_ACTION:
                $this->inventory($content);
                break;
            case self::NETDISCOVERY_ACTION:
                $this->networkDiscovery($content); //XML handle here
                break;
            case self::SNMP_QUERY:
            case self::OLD_SNMP_QUERY:
            case self::NETINV_ACTION:
                $this->networkInventory($content);
                break;
            case self::REGISTER_ACTION:
            case self::CONFIG_ACTION:
            case self::ESX_ACTION:
            case self::COLLECT_ACTION:
            case self::DEPLOY_ACTION:
            case self::WOL_ACTION:
            default:
                $this->addError("Query '$query' is not supported.", 501);
                return false;
        }
        return true;
    }
```

in ```$this->networkDiscovery```.

GLPI uses the ``Hooks::NETWORK_DISCOVERY`` HOOK

```php
   public function networkDiscovery($data)
    {
        $this->network_inventory_mode = Hooks::NETWORK_DISCOVERY;
        $this->is_discovery = true;
        $this->network($data);
    }
```

Then ```this->network($data)``` still returns the XML in the native inventory because the plugin does nothing with it ($hook_response == $hook_params)

```php
    public function network($data)
    {
        $this->inventory = new Inventory();
        $this->inventory
            ->setDiscovery($this->isDiscovery())
            ->setData($data, $this->getMode());

        $response = [];
        $hook_params = [
            'mode' => $this->getMode(),
            'inventory' => $this->inventory,
            'deviceid' => $this->getDeviceID(),
            'response' => $response,
            'query' => $this->query
        ];

        $hook_response = Plugin::doHookFunction(
            $this->network_inventory_mode,
            $hook_params
        );

        if ($hook_response == $hook_params) {
            //no hook, use native capabilities
            $this->inventory($data); //XML send to GLPI here
        } else {
            //try to use hook response
            if (isset($hook_response['response']) && count($hook_response['response'])) {
                $this->addToResponse($response);
            } else if (isset($hook_response['errors']) && count($hook_response['errors'])) {
                $this->addError($hook_response['errors'], 400);
            } else {
                //nothing expected happens; this is an error
                $this->addError("Query '" . $this->query . "' is not supported.", 400);
            }
        }
    }
```

So we'd have to modify ```inventory_format``` and the plugin 

I don't know if this should be reported as a rejected piece of equipment.

Since it doesn't even respond

It should arrive (and be handled) here

https://github.com/glpi-project/glpi-inventory-plugin/blob/f706964a0c715ca0c2e8d33a841e1fbda36f4a2e/inc/communicationnetworkinventory.class.php#L143-L154

**Comment by stonebuzz** [comment]
I'm closing this one in favor of https://github.com/glpi-project/glpi-inventory-plugin/pull/402

**Pull request closed without merging**
