### PR TITLE
Fix migration from fusioninventory plugin; fixes #16

### LINKED ISSUE #16: Installation Failed
Hello,
I try to install the plugins into my glpi and when the database migrate, i've this issue. (Sorry for my english i'm a french guy)

This is the log file

Migration Classname : Migration (0 seconde)
Update of plugin GLPI Inventory (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agents (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agentmodules (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (0 seconde)
Ajout des index d'unicité - glpi_plugin_glpiinventory_configs (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_entities (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ignoredimportdevices (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_rulematchedlogs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_unmanageds (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercriterias (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputerblacklists (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercomputers (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerlicenseinfos (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerremotemanagements (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventorynames (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventories (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwares (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwareversions (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configlogfields (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (4 secondes)
Clean printers (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_statediscoveries (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deployfiles (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_entities (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_groups (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_profiles (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_users (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploymirrors (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_staticdatas (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_dynamicdatas (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentials (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentialips (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_tasks (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjoblogs (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobstates (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslots (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslotentries (7 secondes)
Add Crontasks (7 secondes)
Traitement terminé. (7 secondes)
Migration Classname : Migration (0 seconde)
Use core capabilities (0 seconde)
Use core SNMP credentials (0 seconde)
Use core network ports (0 seconde)
Use core network equipments (0 seconde)
Use core printers (0 seconde)
Use core printer logs (0 seconde)
Use core networkports logs (0 seconde)
Use core network ports types (0 seconde)
Use core agent (0 seconde)
- Erreur durant l'éxecution de la requête : UPDATE `glpi_plugin_glpiinventory_printers` SET `plugin_glpiinventory_agents_id` = '0' WHERE `plugin_glpiinventory_agents_id` = '1' - L'erreur est Table 'glpidb.glpi_plugin_glpiinventory_printers' doesn't exist

Thank's for your help

### PR DESCRIPTION
**Pull request by cedric-anne**
1. Ensure migration can be replayed.
2. Migrate agent firsts.
3. Fix invalid update of printers agents (printers are not linked to agents).

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Comment by cedric-anne** [comment]
Was not failing in tests because test DB does not contains any agent, so `$agents_mapping` is empty and this piece of code is not executed.

**Comment by cedric-anne** [comment]
> Was not failing in tests because test DB does not contains any agent, so `$agents_mapping` is empty and this piece of code is not executed.

Not really sure about that finally, should have this agent in DB: ``` INSERT INTO `glpi_plugin_fusioninventory_agents` (`id`, `entities_id`, `is_recursive`, `name`, `last_contact`, `version`, `lock`, `device_id`, `items_id`, `token`, `useragent`, `tag`) VALUES
(1, 0, 1, 'port004.bureau.siprossii.com-2012-12-20-16-27-27', '2013-03-28 08:34:48', '{"INVENTORY":"v2.2.7-2"}', 0, 'port004.bureau.siprossii.com-2012-12-20-16-27-27', 1, 'PTRBDGED', 'FusionInventory-Agent_v2.2.7-2', NULL); ```

**Comment by cedric-anne** [comment]
Found it. Some queries were not executed due to the fact that created core Agents had same id as existing plugin agents. Forcing auto-increment of GLPI core tables (to ensure differences in generated IDs) result in tests failure. See https://github.com/glpi-project/glpi-inventory-plugin/runs/4553712937?check_suite_focus=true#step:18:13

**Comment by cedric-anne** [comment]
I did not find why some tests are failing when autoincrement is changed. It may be a bug in tasks jobs preparation, or in tests themselves.

I reverted this change, but other changes are mandatory to fix migration when ran on a GLPI that already has created agents.

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
